#spring:
#  desafiodev:
#    username: postgres
#    password: 245594
#    url: jdbc:postgresql://localhost:5432/desafiodev
#    org.postgresql.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL94Dialect
